version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    poetry: "1.7.1"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - method: poetry
      path: .
      extra_requirements:
        - docs

# Required for Poetry support
search:
  ignore:
    - poetry.lock