# Qdrant Vector Database Configuration
name: QDRANT_CONFIG
description: "Configuration for Qdrant vector database"

# Connection settings
connection:
  host: "localhost"
  port: 6333
  use_grpc: false
  api_key: null  # Set if using authentication

# Collection settings
collections:
  hmdb_metabolites:
    vector_size: 384
    distance: "Cosine"
    on_disk: false
    indexes:
      - field: "hmdb_id"
        type: "keyword"
      - field: "name"
        type: "text"

# Search settings
search:
  default_limit: 10
  default_threshold: 0.75
  timeout_seconds: 5

# Embedding settings
embedding:
  model: "BAAI/bge-small-en-v1.5"
  batch_size: 100
  normalize: true