name: THREE_WAY_METABOLOMICS_MAPPING
description: "Map metabolites across Israeli10K, Arivale, and UKBB using Nightingale NMR commonality and tiered approach"

# Key insight: Israeli10K and UKBB both use Nightingale NMR system
# This provides a strong bridge for direct mapping between these two
# Arivale uses different system but has rich identifier metadata (HMDB, KEGG, PubChem)

steps:
  # Step 1: Load all three metabolomics datasets
  - name: load_metabolomics_datasets
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/israeli10k/israeli10k_metabolomics_metadata.csv
        identifier_column: tabular_field_name
        additional_columns: 
          - nightingale_metabolomics_original_name
          - description_string
        output_key: israeli10k_metabolites

  - name: load_ukbb_nmr_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_NMR_Meta.tsv
        identifier_column: title
        additional_columns:
          - field_id
          - Group
          - Subgroup
        output_key: ukbb_metabolites

  - name: load_arivale_metabolomics
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/metabolomics_metadata.tsv
        identifier_column: BIOCHEMICAL_NAME
        additional_columns:
          - HMDB
          - KEGG
          - PUBCHEM
          - CAS
          - SUPER_PATHWAY
          - SUB_PATHWAY
        output_key: arivale_metabolites

  # Step 2: Direct Nightingale matching between Israeli10K and UKBB
  - name: nightingale_direct_match
    action:
      type: NIGHTINGALE_NMR_MATCH
      params:
        source_dataset_key: israeli10k_metabolites
        target_dataset_key: ukbb_metabolites
        source_nightingale_column: nightingale_metabolomics_original_name
        target_title_column: title
        match_strategy: fuzzy  # High threshold since both use Nightingale
        confidence_threshold: 0.95
        output_key: israeli10k_ukbb_nightingale_matches
        unmatched_source_key: israeli10k_unmatched
        unmatched_target_key: ukbb_unmatched

  # Step 3: Create Nightingale-to-standard mapping reference
  - name: build_nightingale_reference
    action:
      type: BUILD_NIGHTINGALE_REFERENCE
      params:
        israeli10k_data: israeli10k_metabolites
        ukbb_data: ukbb_metabolites
        matched_pairs: israeli10k_ukbb_nightingale_matches
        output_key: nightingale_reference_map
        export_reference: true
        reference_file: /home/ubuntu/biomapper/data/results/metabolomics/nightingale_reference.csv

  # Step 4: Map Arivale to Nightingale using multiple strategies
  # 4a. Direct biochemical name matching
  - name: arivale_direct_match
    action:
      type: METABOLITE_NAME_MATCH
      params:
        source_dataset_key: arivale_metabolites
        target_reference: nightingale_reference_map
        source_column: BIOCHEMICAL_NAME
        match_threshold: 0.85
        output_key: arivale_nightingale_direct
        unmatched_key: arivale_unmatched_tier1

  # 4b. API resolution for unmatched Arivale metabolites
  - name: arivale_api_enrichment
    action:
      type: METABOLITE_API_ENRICHMENT
      params:
        input_key: arivale_unmatched_tier1
        api_services:
          - service: hmdb
            input_column: HMDB
            output_fields: [common_name, synonyms, kegg_id, traditional_iupac]
          - service: pubchem
            input_column: PUBCHEM
            output_fields: [iupac_name, synonyms, inchikey]
        batch_size: 50
        cache_results: true
        output_key: arivale_enriched

  # 4c. Match enriched Arivale data to Nightingale reference
  - name: arivale_enriched_match
    action:
      type: ENRICHED_METABOLITE_MATCH
      params:
        enriched_dataset: arivale_enriched
        target_reference: nightingale_reference_map
        match_fields: [common_name, synonyms, iupac_name]
        threshold: 0.8
        output_key: arivale_nightingale_api
        unmatched_key: arivale_unmatched_tier2

  # 4d. RAG + LLM for remaining unmatched
  - name: semantic_metabolite_match
    action:
      type: SEMANTIC_METABOLITE_MATCH
      params:
        unmatched_dataset: arivale_unmatched_tier2
        reference_map: nightingale_reference_map
        context_fields:
          arivale: [SUPER_PATHWAY, SUB_PATHWAY, BIOCHEMICAL_NAME]
          nightingale: [description_string, Group, Subgroup]
        embedding_model: text-embedding-ada-002
        llm_model: gpt-4
        confidence_threshold: 0.75
        include_reasoning: true
        output_key: arivale_nightingale_semantic

  # Step 5: Combine all matches with provenance
  - name: combine_three_way_matches
    action:
      type: COMBINE_METABOLITE_MATCHES
      params:
        nightingale_pairs: israeli10k_ukbb_nightingale_matches
        arivale_mappings:
          - key: arivale_nightingale_direct
            tier: direct
            method: name_matching
          - key: arivale_nightingale_api
            tier: api_enriched
            method: synonym_matching
          - key: arivale_nightingale_semantic
            tier: semantic
            method: llm_validated
        output_key: three_way_matches
        track_provenance: true

  # Step 6: Calculate comprehensive statistics
  - name: calculate_three_way_overlap
    action:
      type: CALCULATE_THREE_WAY_OVERLAP
      params:
        input_key: three_way_matches
        dataset_names:
          - Israeli10K
          - Arivale
          - UKBB
        confidence_threshold: 0.8
        output_dir: /home/ubuntu/biomapper/data/results/metabolomics
        mapping_combo_id: Israeli10K_Arivale_UKBB
        generate_visualizations:
          - venn_diagram_3way
          - confidence_heatmap
          - provenance_sankey
          - nightingale_coverage_chart
        output_key: three_way_statistics

  # Step 7: Generate comprehensive report
  - name: generate_metabolomics_report
    action:
      type: GENERATE_METABOLOMICS_REPORT
      params:
        statistics_key: three_way_statistics
        matches_key: three_way_matches
        nightingale_reference: nightingale_reference_map
        output_dir: /home/ubuntu/biomapper/data/results/metabolomics
        report_format: markdown
        include_sections:
          - executive_summary
          - nightingale_nmr_analysis
          - tiered_matching_results
          - confidence_analysis
          - provenance_breakdown
          - unmatched_analysis
          - recommendations
          - technical_appendix
        export_formats:
          - markdown
          - html
          - pdf