name: example_organized_outputs
description: Example strategy demonstrating organized local and cloud outputs
metadata:
  id: example_organized_outputs
  name: Example Organized Outputs Strategy
  version: 2.0.0
  entity_type: metabolites
  quality_tier: example
parameters:
  source_file: /home/ubuntu/biomapper/data/test_data/test_metabolites.tsv
  gdrive_folder_id: 1oQ7CczccH2a6oYYFMo_sf8fXtxF8au_D
steps:
- name: load_metabolites
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${parameters.source_file}
      identifier_column: metabolite_id
      output_key: metabolites
      additional_columns:
      - name
      - inchikey
      - chebi_id
      - kegg_id
- name: export_local_organized
  action:
    type: EXPORT_DATASET_V2
    params:
      input_key: metabolites
      output_path: metabolites_harmonized.tsv
      use_organized_structure: true
      format: tsv
      include_metadata: true
      create_summary: true
- name: export_json_organized
  action:
    type: EXPORT_DATASET_V2
    params:
      input_key: metabolites
      output_path: metabolites_harmonized.json
      use_organized_structure: true
      format: json
      create_summary: false
- name: sync_to_gdrive_organized
  action:
    type: SYNC_TO_GOOGLE_DRIVE_V2
    params:
      drive_folder_id: ${parameters.gdrive_folder_id}
      credentials_path: ${GOOGLE_APPLICATION_CREDENTIALS}
      auto_organize: true
      sync_context_outputs: true
      create_subfolder: true
      description: Organized metabolite harmonization results
- name: export_classic
  action:
    type: EXPORT_DATASET
    params:
      input_key: metabolites
      output_path: /tmp/biomapper/classic_output/metabolites_classic.tsv
      format: tsv
- name: sync_classic
  action:
    type: SYNC_TO_GOOGLE_DRIVE
    params:
      drive_folder_id: ${parameters.gdrive_folder_id}
      credentials_path: ${GOOGLE_APPLICATION_CREDENTIALS}
      input_files:
      - /tmp/biomapper/classic_output/metabolites_classic.tsv
      create_subfolder: true
      subfolder_name: classic_export_${timestamp}
