name: NIGHTINGALE_NMR_MATCH_EXAMPLE
description: |
  Example strategy demonstrating UKBB Nightingale NMR biomarker matching.
  Maps Nightingale Health platform biomarker names to standard identifiers (HMDB/LOINC).

parameters:
  # Input/Output files
  nmr_data_file: "${DATA_DIR}/ukbb_nmr_biomarkers.tsv"
  reference_file: "${DATA_DIR}/references/nightingale_nmr_reference.csv"
  output_dir: "${OUTPUT_DIR}/nightingale_nmr_results"
  
  # Matching configuration
  biomarker_column: "biomarker"
  unit_column: "unit"
  target_format: "both"  # hmdb, loinc, or both
  match_threshold: 0.85
  use_abbreviations: true
  
  # Output configuration
  add_metadata: true
  include_units: true
  include_categories: true

steps:
  - name: load_ukbb_nmr_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.nmr_data_file}"
        identifier_column: "${parameters.biomarker_column}"
        identifier_type: "nightingale_biomarker"
        additional_columns:
          - value
          - unit
          - participant_id
        output_key: ukbb_nmr_raw
    
  - name: match_nightingale_biomarkers
    action:
      type: NIGHTINGALE_NMR_MATCH
      params:
        input_key: ukbb_nmr_raw
        output_key: nightingale_matched
        
        # Source configuration
        biomarker_column: "${parameters.biomarker_column}"
        unit_column: "${parameters.unit_column}"
        
        # Reference file
        reference_file: "${parameters.reference_file}"
        use_cached_reference: true
        
        # Target format
        target_format: "${parameters.target_format}"
        
        # Matching configuration
        match_threshold: "${parameters.match_threshold}"
        use_abbreviations: "${parameters.use_abbreviations}"
        case_sensitive: false
        
        # Output options
        add_metadata: "${parameters.add_metadata}"
        include_units: "${parameters.include_units}"
        include_categories: "${parameters.include_categories}"
  
  - name: export_matched_results
    action:
      type: EXPORT_DATASET
      params:
        dataset_key: nightingale_matched
        output_file: "${parameters.output_dir}/matched_biomarkers.tsv"
        format: "tsv"
        include_metadata: true
  
  - name: filter_lipids
    action:
      type: FILTER_DATASET
      params:
        input_key: nightingale_matched
        output_key: lipid_biomarkers
        filter_column: "category"
        filter_value: "lipids"
        filter_type: "equals"
  
  - name: filter_amino_acids
    action:
      type: FILTER_DATASET
      params:
        input_key: nightingale_matched
        output_key: amino_acid_biomarkers
        filter_column: "category"
        filter_value: "amino_acids"
        filter_type: "equals"
  
  - name: export_lipids
    action:
      type: EXPORT_DATASET
      params:
        dataset_key: lipid_biomarkers
        output_file: "${parameters.output_dir}/lipid_biomarkers.tsv"
        format: "tsv"
        include_metadata: true
  
  - name: export_amino_acids
    action:
      type: EXPORT_DATASET
      params:
        dataset_key: amino_acid_biomarkers
        output_file: "${parameters.output_dir}/amino_acid_biomarkers.tsv"
        format: "tsv"
        include_metadata: true
  
  - name: generate_summary_report
    action:
      type: GENERATE_METABOLOMICS_REPORT
      params:
        matched_dataset_key: nightingale_matched
        report_type: "summary"
        output_file: "${parameters.output_dir}/nightingale_match_report.html"
        include_statistics: true
        include_category_breakdown: true
        include_unmatched_list: true

output:
  matched_biomarkers: "${parameters.output_dir}/matched_biomarkers.tsv"
  lipid_biomarkers: "${parameters.output_dir}/lipid_biomarkers.tsv"
  amino_acid_biomarkers: "${parameters.output_dir}/amino_acid_biomarkers.tsv"
  summary_report: "${parameters.output_dir}/nightingale_match_report.html"

metadata:
  version: "1.0.0"
  tags:
    - ukbb
    - nightingale
    - nmr
    - metabolomics
    - biomarker_matching
  requirements:
    - nightingale_nmr_reference.csv file in references directory
    - UKBB NMR data with biomarker column
  notes: |
    This strategy demonstrates the NIGHTINGALE_NMR_MATCH action for mapping
    UK Biobank NMR metabolomics data from the Nightingale Health platform
    to standard identifiers (HMDB, LOINC).
    
    The action handles:
    - Exact matching for known biomarkers
    - Fuzzy matching for variations
    - Lipoprotein particle pattern recognition
    - Abbreviation expansion
    - Category classification
    - Unit standardization