metadata:
  id: "prot_demo_normalize_demo_v1_base"
  name: "Protein Normalization Demo Strategy"
  version: "1.0.0"
  created: "2025-08-07"
  author: "BiomapperStrategyAssistant"
  entity_type: "proteins"
  source_dataset: "demo"
  target_dataset: "normalized"
  bridge_type: ["normalization"]
  quality_tier: "experimental"
  validation_status: "pending"
  expected_match_rate: 1.0
  description: "Demonstrates PROTEIN_NORMALIZE_ACCESSIONS action functionality"
  tags: ["demo", "normalization", "protein"]

parameters:
  output_dir: "${OUTPUT_DIR:-/tmp/biomapper/outputs}"
  demo_data_file: "/tmp/demo_proteins.tsv"

steps:
  - name: load_demo_proteins
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.demo_data_file}"
        identifier_column: "uniprot_id"
        output_key: "demo_proteins"

  - name: normalize_protein_accessions
    action:
      type: PROTEIN_NORMALIZE_ACCESSIONS
      params:
        input_key: "demo_proteins"
        id_columns: ["uniprot_id"]
        strip_isoforms: true
        strip_versions: true
        validate_format: true
        output_key: "normalized_proteins"
        add_normalization_log: true

  - name: export_results
    action:
      type: EXPORT_DATASET
      params:
        input_key: "normalized_proteins"
        file_path: "${parameters.output_dir}/normalized_proteins.tsv"
        file_format: "tsv"