name: test_metabolite_simple
description: Simple test strategy for metabolite processing
metadata:
  id: test_metabolite_simple
  name: Test Metabolite Processing
  version: 1.0.0
  entity_type: metabolites
  quality_tier: test
parameters:
  source_file: /home/ubuntu/biomapper/data/test_data/test_metabolites.tsv
  output_dir: /tmp/biomapper/test_output
  cache_dir: /tmp/biomapper/cache
steps:
  - name: load_metabolites
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.source_file}"
        identifier_column: metabolite_id
        output_key: test_metabolites
        additional_columns:
          - name
          - inchikey
          - smiles
        
  - name: normalize_hmdb
    action:
      type: METABOLITE_NORMALIZE_HMDB
      params:
        input_key: test_metabolites
        output_key: normalized_metabolites
        id_column: metabolite_id
        
  - name: export_results
    action:
      type: EXPORT_DATASET
      params:
        input_key: normalized_metabolites
        output_file: "${parameters.output_dir}/normalized_metabolites.tsv"
        format: tsv