name: test_simple_v2.2
description: Simple test strategy for v2.2 features
parameters:
  source_file: /tmp/test_source.txt
  target_file: /tmp/test_target.txt
  output_dir: /tmp/test_output
steps:
- name: load_source
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${parameters.source_file}
      identifier_column: uniprot_id
      output_key: source_data
- name: load_target
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${parameters.target_file}
      identifier_column: id
      output_key: target_data
- name: export_test
  action:
    type: EXPORT_DATASET
    params:
      input_key: source_data
      output_path: ${parameters.output_dir}/test_export.tsv
      format: tsv
