name: THREE_WAY_METABOLOMICS_COMPLETE
description: "Complete three-way metabolomics mapping with all new components"
version: "1.0.0"

# Parameters that can be overridden
parameters:
  # File paths
  israeli10k_file: "/procedure/data/local_data/MAPPING_ONTOLOGIES/israeli10k/israeli10k_metabolomics_metadata.csv"
  ukbb_file: "/procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_NMR_Meta.tsv"
  arivale_file: "/procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/metabolomics_metadata.tsv"
  
  # Output directory
  output_dir: "/home/ubuntu/biomapper/data/results/metabolomics_three_way"
  
  # Matching thresholds
  nightingale_threshold: 0.95
  baseline_threshold: 0.85
  api_threshold: 0.80
  semantic_threshold: 0.75
  
  # API configuration
  api_batch_size: 50
  max_llm_calls: 100

steps:
  # ===== Phase 1: Data Loading =====
  - name: load_israeli10k
    description: "Load Israeli10K metabolomics metadata"
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.israeli10k_file}"
        identifier_column: "tabular_field_name"
        additional_columns:
          - "nightingale_metabolomics_original_name"
          - "field_string"
          - "description_string"
        output_key: "israeli10k_data"

  - name: load_ukbb
    description: "Load UKBB NMR metabolomics data"
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.ukbb_file}"
        identifier_column: "title"
        additional_columns:
          - "field_id"
          - "Group"
          - "Subgroup"
        output_key: "ukbb_data"

  - name: load_arivale
    description: "Load Arivale metabolomics data"
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.arivale_file}"
        identifier_column: "BIOCHEMICAL_NAME"
        additional_columns:
          - "HMDB"
          - "KEGG"
          - "PUBCHEM"
          - "CAS"
          - "SUPER_PATHWAY"
          - "SUB_PATHWAY"
        output_key: "arivale_data"

  # ===== Phase 2: Nightingale Platform Harmonization =====
  - name: match_nightingale_platforms
    description: "Match Israeli10K and UKBB using Nightingale NMR commonality"
    action:
      type: NIGHTINGALE_NMR_MATCH
      params:
        source_dataset_key: "israeli10k_data"
        target_dataset_key: "ukbb_data"
        source_nightingale_column: "nightingale_metabolomics_original_name"
        target_title_column: "title"
        match_strategy: "fuzzy"
        confidence_threshold: "${parameters.nightingale_threshold}"
        output_key: "nightingale_matches"
        unmatched_source_key: "israeli10k_unmatched"
        unmatched_target_key: "ukbb_unmatched"

  - name: build_nightingale_reference
    description: "Build unified Nightingale reference from matched pairs"
    action:
      type: BUILD_NIGHTINGALE_REFERENCE
      params:
        israeli10k_data: "israeli10k_data"
        ukbb_data: "ukbb_data"
        matched_pairs: "nightingale_matches"
        output_key: "nightingale_reference"
        export_csv: true
        csv_path: "${parameters.output_dir}/nightingale_reference.csv"
        include_metadata: true

  # ===== Phase 3: Progressive Arivale Matching =====
  
  ## Tier 1: Direct name matching
  - name: arivale_baseline_match
    description: "Baseline fuzzy matching for Arivale metabolites"
    action:
      type: BASELINE_FUZZY_MATCH
      params:
        source_dataset_key: "arivale_data"
        target_dataset_key: "nightingale_reference"
        source_column: "BIOCHEMICAL_NAME"
        target_column: "unified_name"
        threshold: "${parameters.baseline_threshold}"
        algorithm: "token_set_ratio"
        output_key: "baseline_matches"
        unmatched_key: "unmatched.baseline.arivale_data"
        track_metrics: true
        metrics_key: "metrics.baseline"

  ## Tier 2: API enrichment
  - name: arivale_api_enrichment
    description: "Multi-API enrichment for unmatched Arivale metabolites"
    action:
      type: METABOLITE_API_ENRICHMENT
      params:
        unmatched_dataset_key: "unmatched.baseline.arivale_data"
        target_dataset_key: "nightingale_reference"
        api_services:
          - service: "hmdb"
            input_column: "HMDB"
            output_fields: ["common_name", "synonyms", "iupac_name", "inchikey"]
            timeout: 30
          - service: "pubchem"
            input_column: "PUBCHEM"
            output_fields: ["IUPACName", "synonyms", "InChIKey"]
            timeout: 30
          - service: "cts"
            input_column: "KEGG"
            output_fields: ["chemical_name", "synonyms"]
            timeout: 20
        target_column: "unified_name"
        match_threshold: "${parameters.api_threshold}"
        batch_size: "${parameters.api_batch_size}"
        output_key: "api_matches"
        unmatched_key: "unmatched.api.arivale_data"
        track_metrics: true
        metrics_key: "metrics.api"

  ## Tier 3: Semantic/LLM matching
  - name: arivale_semantic_match
    description: "Semantic matching using embeddings and LLM validation"
    action:
      type: SEMANTIC_METABOLITE_MATCH
      params:
        unmatched_dataset: "unmatched.api.arivale_data"
        reference_map: "nightingale_reference"
        context_fields:
          arivale: ["BIOCHEMICAL_NAME", "SUPER_PATHWAY", "SUB_PATHWAY"]
          nightingale: ["unified_name", "description_string", "category"]
        embedding_model: "text-embedding-ada-002"
        llm_model: "gpt-4"
        confidence_threshold: "${parameters.semantic_threshold}"
        embedding_similarity_threshold: 0.85
        include_reasoning: true
        max_llm_calls: "${parameters.max_llm_calls}"
        batch_size: 10
        output_key: "semantic_matches"
        unmatched_key: "final_unmatched"

  # ===== Phase 4: Three-Way Integration =====
  - name: combine_all_matches
    description: "Combine all matching results with provenance tracking"
    action:
      type: COMBINE_METABOLITE_MATCHES
      params:
        nightingale_pairs: "nightingale_matches"
        arivale_mappings:
          - key: "baseline_matches"
            tier: "direct"
            method: "baseline_fuzzy"
            confidence_weight: 1.0
          - key: "api_matches"
            tier: "api_enriched"
            method: "multi_api"
            confidence_weight: 0.9
          - key: "semantic_matches"
            tier: "semantic"
            method: "llm_validated"
            confidence_weight: 0.8
        output_key: "three_way_matches"
        track_provenance: true
        min_confidence: 0.5

  # ===== Phase 5: Analysis & Reporting =====
  - name: calculate_overlap_statistics
    description: "Calculate comprehensive three-way overlap statistics"
    action:
      type: CALCULATE_THREE_WAY_OVERLAP
      params:
        input_key: "three_way_matches"
        dataset_names: ["Israeli10K", "UKBB", "Arivale"]
        confidence_threshold: 0.8
        output_dir: "${parameters.output_dir}/statistics"
        mapping_combo_id: "Israeli10K_UKBB_Arivale_complete"
        generate_visualizations:
          - "venn_diagram_3way"
          - "confidence_heatmap"
          - "overlap_progression_chart"
        output_key: "three_way_statistics"
        export_detailed_results: true

  - name: generate_final_report
    description: "Generate comprehensive metabolomics mapping report"
    action:
      type: GENERATE_METABOLOMICS_REPORT
      params:
        statistics_key: "three_way_statistics"
        matches_key: "three_way_matches"
        nightingale_reference: "nightingale_reference"
        metrics_keys:
          - "metrics.baseline"
          - "metrics.api"
          - "metrics.semantic"
        output_dir: "${parameters.output_dir}/reports"
        report_format: "markdown"
        include_sections:
          - "executive_summary"
          - "methodology_overview"
          - "dataset_overview"
          - "progressive_matching_results"
          - "three_way_overlap_analysis"
          - "confidence_distribution"
          - "quality_metrics"
          - "recommendations"
        export_formats:
          - "markdown"
          - "html"
          - "json"
        include_visualizations: true
        max_examples: 10

# Validation expectations
validation:
  min_nightingale_matches: 40
  min_three_way_overlap: 50
  max_low_confidence_percentage: 30
  required_outputs:
    - "nightingale_reference.csv"
    - "three_way_statistics"
    - "final_report.md"