name: "ARIVALE_SPOKE_PROTEIN_MAPPING"
description: "Map Arivale proteins to SPOKE knowledge graph with historical resolution"
  
steps:
  - name: load_arivale_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/proteomics_metadata.tsv"
        identifier_column: "uniprot"
        output_key: "arivale_proteins"
        
  - name: load_spoke_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/spoke_ontologies/spoke_protein.csv"
        identifier_column: "identifier"
        output_key: "spoke_proteins"
        
  - name: merge_datasets
    action:
      type: MERGE_WITH_UNIPROT_RESOLUTION
      params:
        source_dataset_key: "arivale_proteins"
        target_dataset_key: "spoke_proteins"
        source_id_column: "uniprot"
        target_id_column: "identifier"
        output_key: "arivale_spoke_merged"
        
  - name: analyze_overlap
    action:
      type: CALCULATE_SET_OVERLAP
      params:
        input_key: "arivale_spoke_merged"
        source_name: "Arivale"
        target_name: "SPOKE"
        mapping_combo_id: "Arivale_SPOKE"
        confidence_threshold: 0.8
        output_dir: "/home/ubuntu/biomapper/data/results"
        output_key: "arivale_spoke_analysis"