description: Map UK Biobank proteins to Quantitative Imaging Network with historical
  resolution
name: UKBB_TO_QIN_PROTEIN_MAPPING
steps:
- action:
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_Protein_Meta.tsv
      identifier_column: UniProt
      output_key: ukbb_proteins
    type: LOAD_DATASET_IDENTIFIERS
  name: load_ukbb_data
- action:
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/isb_osp/qin_osps.csv
      identifier_column: uniprot
      output_key: qin_proteins
    type: LOAD_DATASET_IDENTIFIERS
  name: load_qin_data
- action:
    params:
      output_key: ukbb_qin_merged
      source_dataset_key: ukbb_proteins
      source_id_column: UniProt
      target_dataset_key: qin_proteins
      target_id_column: uniprot
    type: MERGE_WITH_UNIPROT_RESOLUTION
  name: merge_datasets
- action:
    params:
      confidence_threshold: 0.8
      input_key: ukbb_qin_merged
      mapping_combo_id: UKBB_QIN
      output_dir: /home/ubuntu/biomapper/data/results
      output_key: ukbb_qin_analysis
      source_name: UKBB
      target_name: QIN
    type: CALCULATE_SET_OVERLAP
  name: analyze_overlap
