# Sample mapping strategy demonstrating typed action compatibility
# This strategy works with both the legacy and typed ExecuteMappingPathAction

name: "uniprot_to_ensembl_typed_demo"
description: "Demo strategy showing typed action compatibility"
version: "1.0"
author: "Biomapper Team"

# Source and target endpoint configuration
source_endpoint:
  name: "uniprot_proteins"
  type: "PROTEIN_UNIPROT"
  description: "UniProt protein identifiers"

target_endpoint:
  name: "ensembl_proteins"
  type: "PROTEIN_ENSEMBL"
  description: "Ensembl protein identifiers"

# Execution settings
settings:
  batch_size: 100
  min_confidence: 0.8
  use_cache: true
  max_retries: 3

# Strategy steps
steps:
  - name: "load_source_identifiers"
    action: "LOAD_ENDPOINT_IDENTIFIERS"
    description: "Load UniProt protein identifiers"
    params:
      endpoint_name: "uniprot_proteins"
      limit: 1000
    
  - name: "execute_mapping_path"
    action: "EXECUTE_MAPPING_PATH"  # This will use the typed version (backward compatible)
    description: "Map UniProt to Ensembl using predefined mapping path"
    params:
      path_name: "uniprot_to_ensembl"
      batch_size: 250  # Override default batch size
      min_confidence: 0.75  # Override default confidence threshold
    
  - name: "generate_summary"
    action: "GENERATE_MAPPING_SUMMARY"
    description: "Generate mapping summary report"
    params:
      include_unmapped: true
      include_provenance: true
      
  - name: "export_results"
    action: "EXPORT_RESULTS"
    description: "Export mapping results to file"
    params:
      format: "csv"
      filename: "uniprot_to_ensembl_results.csv"
      include_provenance: true

# Expected outcomes
expected_results:
  min_mapped_percentage: 80
  max_execution_time_seconds: 300
  required_output_fields:
    - "input_identifiers"
    - "output_identifiers"
    - "provenance"
    - "details"