description: Map Arivale proteins to UK Biobank with historical resolution
name: ARIVALE_TO_UKBB_PROTEIN_MAPPING
steps:
- action:
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/proteomics_metadata.tsv
      identifier_column: uniprot
      output_key: arivale_proteins
    type: LOAD_DATASET_IDENTIFIERS
  name: load_arivale_data
- action:
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_Protein_Meta.tsv
      identifier_column: UniProt
      output_key: ukbb_proteins
    type: LOAD_DATASET_IDENTIFIERS
  name: load_ukbb_data
- action:
    params:
      output_key: arivale_ukbb_merged
      source_dataset_key: arivale_proteins
      source_id_column: uniprot
      target_dataset_key: ukbb_proteins
      target_id_column: UniProt
    type: MERGE_WITH_UNIPROT_RESOLUTION
  name: merge_datasets
- action:
    params:
      confidence_threshold: 0.8
      input_key: arivale_ukbb_merged
      mapping_combo_id: Arivale_UKBB
      output_dir: /home/ubuntu/biomapper/data/results
      output_key: arivale_ukbb_analysis
      source_name: Arivale
      target_name: UKBB
    type: CALCULATE_SET_OVERLAP
  name: analyze_overlap
