description: Map Human Protein Atlas proteins to SPOKE knowledge graph with historical
  resolution
name: HPA_TO_SPOKE_PROTEIN_MAPPING
steps:
- action:
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/isb_osp/hpa_osps.csv
      identifier_column: uniprot
      output_key: hpa_proteins
    type: LOAD_DATASET_IDENTIFIERS
  name: load_hpa_data
- action:
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/spoke_ontologies/spoke_protein.csv
      identifier_column: identifier
      output_key: spoke_proteins
    type: LOAD_DATASET_IDENTIFIERS
  name: load_spoke_data
- action:
    params:
      output_key: hpa_spoke_merged
      source_dataset_key: hpa_proteins
      source_id_column: uniprot
      target_dataset_key: spoke_proteins
      target_id_column: identifier
    type: MERGE_WITH_UNIPROT_RESOLUTION
  name: merge_datasets
- action:
    params:
      confidence_threshold: 0.8
      input_key: hpa_spoke_merged
      mapping_combo_id: HPA_SPOKE
      output_dir: /home/ubuntu/biomapper/data/results
      output_key: hpa_spoke_analysis
      source_name: HPA
      target_name: SPOKE
    type: CALCULATE_SET_OVERLAP
  name: analyze_overlap
