name: UKBB_HPA_PROTEIN_OVERLAP_ANALYSIS
description: "Maps UKBB protein assay IDs to HPA gene names using local files."

steps:
  - name: CONVERT_UKBB_ASSAY_TO_UNIPROT
    action:
      type: LOCAL_ID_CONVERTER
      params:
        input_context_key: "input_identifiers"
        output_context_key: "ukbb_uniprot_ids"
        mapping_file: "/procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_Protein_Meta.tsv"
        source_column: "Assay"
        target_column: "UniProt"
        output_ontology_type: "PROTEIN_UNIPROTKB_AC_ONTOLOGY"

  - name: LOAD_HPA_UNIPROT_IDS
    action:
      type: LOAD_ENDPOINT_IDENTIFIERS
      params:
        endpoint_name: "HPA_PROTEIN_DATA"
        output_context_key: "hpa_uniprot_ids"

  - name: ANALYZE_OVERLAP
    action:
      type: DATASET_OVERLAP_ANALYZER
      params:
        dataset1_context_key: "ukbb_uniprot_ids"
        dataset2_context_key: "hpa_uniprot_ids"
        output_context_key: "overlapping_uniprot_ids"
        dataset1_name: "UKBB"
        dataset2_name: "HPA"
        generate_statistics: True

  - name: CONVERT_UNIPROT_TO_HPA_GENE
    action:
      type: LOCAL_ID_CONVERTER
      params:
        input_context_key: "overlapping_uniprot_ids"
        output_context_key: "final_hpa_genes"
        mapping_file: "/procedure/data/local_data/MAPPING_ONTOLOGIES/isb_osp/hpa_osps.csv"
        source_column: "uniprot"
        target_column: "gene"
        output_ontology_type: "HPA_GENE_ONTOLOGY"
