name: "UKBB_HPA_PROTEIN_MAPPING"
description: "Map UK Biobank proteins to Human Protein Atlas with historical resolution"
  
steps:
  - name: load_arivale_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/proteomics_metadata.tsv"
        identifier_column: "uniprot"
        output_key: "arivale_proteins"
        
  - name: load_hpa_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/isb_osp/hpa_osps.csv"
        identifier_column: "uniprot"
        output_key: "hpa_proteins"
        
  - name: load_ukbb_data
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_Protein_Meta.tsv"
        identifier_column: "UniProt"
        output_key: "ukbb_proteins"
        
  - name: merge_arivale_hpa
    action:
      type: MERGE_WITH_UNIPROT_RESOLUTION
      params:
        source_dataset_key: "arivale_proteins"
        target_dataset_key: "hpa_proteins"
        source_id_column: "uniprot"
        target_id_column: "uniprot"
        output_key: "arivale_hpa_merged"
        
  - name: merge_ukbb_hpa
    action:
      type: MERGE_WITH_UNIPROT_RESOLUTION
      params:
        source_dataset_key: "ukbb_proteins"
        target_dataset_key: "hpa_proteins"
        source_id_column: "UniProt"
        target_id_column: "uniprot"
        output_key: "ukbb_hpa_merged"
        
  - name: analyze_arivale_hpa_overlap
    action:
      type: CALCULATE_SET_OVERLAP
      params:
        input_key: "arivale_hpa_merged"
        source_name: "Arivale"
        target_name: "HPA"
        mapping_combo_id: "ARIVALE_HPA"
        confidence_threshold: 0.8
        output_dir: "/home/ubuntu/biomapper/data/results"
        output_key: "arivale_hpa_analysis"
        
  - name: analyze_ukbb_hpa_overlap
    action:
      type: CALCULATE_SET_OVERLAP
      params:
        input_key: "ukbb_hpa_merged"
        source_name: "UKBB"
        target_name: "HPA"
        mapping_combo_id: "UKBB_HPA"
        confidence_threshold: 0.8
        output_dir: "/home/ubuntu/biomapper/data/results"
        output_key: "ukbb_hpa_analysis"