"""Add path_execution_log_id to entity_mappings

Revision ID: 555dfdcb35c2
Revises: 05a1cef680a1
Create Date: 2025-06-18 10:49:02.514268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555dfdcb35c2'
down_revision = '05a1cef680a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_execution_log_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_path_execution_log_id', ['path_execution_log_id'], unique=False)
        batch_op.create_foreign_key('fk_entity_mappings_path_execution_log_id', 'path_execution_logs', ['path_execution_log_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_mappings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entity_mappings_path_execution_log_id', type_='foreignkey')
        batch_op.drop_index('idx_path_execution_log_id')
        batch_op.drop_column('path_execution_log_id')

    # ### end Alembic commands ###
