"""Add metadata fields to EntityMapping

Revision ID: 57ffe7f9bdab
Revises: 8ebecfb32984
Create Date: 2025-04-30 17:21:32.762239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57ffe7f9bdab"
down_revision = "8ebecfb32984"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("path_execution_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "source_entity_id", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("path_log_mapping_associations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_path_log_mapping_associations_input_identifier"),
            ["input_identifier"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_path_log_mapping_associations_log_id"),
            ["log_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_path_log_mapping_associations_output_identifier"),
            ["output_identifier"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("path_log_mapping_associations", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_path_log_mapping_associations_output_identifier")
        )
        batch_op.drop_index(batch_op.f("ix_path_log_mapping_associations_log_id"))
        batch_op.drop_index(
            batch_op.f("ix_path_log_mapping_associations_input_identifier")
        )

    with op.batch_alter_table("path_execution_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "source_entity_id", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
