"""Add provenance and logging tables to cache DB

Revision ID: 8ebecfb32984
Revises: bf1c24ebbbec
Create Date: 2025-04-30 00:09:08.910927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebecfb32984'
down_revision = 'bf1c24ebbbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
