name: CHEM_ISR_METAB_TO_SPOKE_SEMANTIC_V1_EXPERIMENTAL
description: Bridge Israeli10k metabolomics to SPOKE clinical labs using semantic matching

metadata:
  # Required fields
  id: "chem_isr_metab_to_spoke_semantic_v1_experimental"
  name: "Israeli10k Metabolomics to SPOKE Labs Semantic Bridge"
  version: "1.0.0"
  created: "2025-08-07"
  author: "biomapper-team"
  entity_type: "chemistry"
  source_dataset: "israeli10k_metabolomics"
  target_dataset: "spoke"
  bridge_type: ["semantic", "fuzzy", "metabolite_chemistry"]
  
  # Quality tracking
  quality_tier: "experimental"
  validation_status: "pending"
  expected_match_rate: 0.40
  actual_match_rate: null
  
  # Data tracking
  source_files:
    - path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/israeli10k/israeli10k_metabolomics_metadata.csv"
      last_updated: "2024-06-01"
      row_count: 234
      data_type: "metabolomics"
  target_files:
    - path: "/procedure/data/local_data/MAPPING_ONTOLOGIES/spoke_ontologies/spoke_clinical_labs.csv"
      last_updated: "2024-10-01"
      row_count: 15000
      standard: "loinc"
  
  # Optional fields
  description: "Experimental strategy bridging metabolomics data to clinical chemistry tests using semantic AI matching"
  tags: ["chemistry", "metabolomics", "semantic", "clinical_labs", "israeli10k", "spoke", "experimental"]
  dependencies: ["biobert_model"]
  supersedes: null
  citation: null
  
  # Chemistry-specific metadata
  test_categories:
    - "glucose_metabolism"
    - "lipid_panel"
    - "amino_acids"
    - "organic_acids"
    - "fatty_acids"

parameters:
  output_dir: "/tmp/biomapper_output"
  semantic_threshold: 0.75
  model: "biobert"

steps:
  - name: load_israeli10k_metabolomics
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${metadata.source_files[0].path}"
        identifier_column: "metabolite_name"
        output_key: "israeli10k_metabolites"
  
  - name: load_spoke_labs
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${metadata.target_files[0].path}"
        identifier_column: "loinc_code"
        output_key: "spoke_labs_raw"
  
  - name: extract_chemistry_related
    action:
      type: CHEMISTRY_EXTRACT_LOINC
      params:
        input_key: "spoke_labs_raw"
        filter_chemistry_related: true
        chemistry_categories:
          - "glucose metabolism"
          - "lipid panel"
          - "amino acids"
          - "organic acids"
          - "fatty acids"
          - "metabolic markers"
        output_key: "chemistry_labs"
  
  - name: fuzzy_metabolite_match
    action:
      type: CHEMISTRY_FUZZY_TEST_MATCH
      params:
        source_key: "israeli10k_metabolites"
        target_key: "chemistry_labs"
        metabolite_to_test_mapping: true
        mapping_rules:
          glucose: ["glucose", "blood sugar", "GLU"]
          cholesterol: ["total cholesterol", "CHOL", "LDL", "HDL"]
          triglycerides: ["triglycerides", "TG", "TRIG"]
          alanine: ["alanine aminotransferase", "ALT", "ALAT"]
          aspartate: ["aspartate aminotransferase", "AST", "ASAT"]
          creatine: ["creatinine", "CREAT"]
          uric_acid: ["uric acid", "UA", "URATE"]
          lactate: ["lactate", "lactic acid", "LAC"]
          pyruvate: ["pyruvate", "pyruvic acid"]
        match_threshold: 0.70
        output_key: "metabolite_chemistry_fuzzy"
  
  - name: semantic_bridge
    action:
      type: SEMANTIC_METABOLITE_MATCH
      params:
        source_key: "metabolite_chemistry_fuzzy"
        target_key: "chemistry_labs"
        model: "${parameters.model}"
        context: "clinical_chemistry"
        threshold: "${parameters.semantic_threshold}"
        semantic_fields:
          - "metabolite_name"
          - "metabolite_description"
          - "pathway_involvement"
        target_fields:
          - "test_name"
          - "test_description"
          - "analyte_name"
        output_key: "semantic_matched"
  
  - name: calculate_overlap
    action:
      type: CALCULATE_SET_OVERLAP
      params:
        dataset1_key: "israeli10k_metabolites"
        dataset2_key: "chemistry_labs"
        output_key: "overlap_statistics"
  
  - name: export_mapping
    action:
      type: EXPORT_DATASET
      params:
        dataset_key: "semantic_matched"
        output_path: "${parameters.output_dir}/israeli10k_metabolomics_spoke_chemistry_semantic.tsv"
        include_semantic_scores: true