name: chem_multi_to_unified_loinc_v1_comprehensive
description: Harmonize chemistry tests from multiple sources into unified LOINC-based
  dataset
metadata:
  id: chem_multi_to_unified_loinc_v1_comprehensive
  name: Multi-Source Chemistry Harmonization
  version: 1.0.0
  created: '2025-08-07'
  author: biomapper-team
  entity_type: chemistry
  source_dataset: multi_vendor
  target_dataset: unified_chemistry
  bridge_type:
  - loinc
  - fuzzy
  - harmonization
  - cross_vendor
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.65
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/chemistries_metadata.tsv
    last_updated: '2024-06-01'
    row_count: 89
    vendor: arivale
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_NMR_Meta.tsv
    last_updated: '2024-05-01'
    row_count: 249
    vendor: ukbb_nmr
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/israeli10k/israeli10k_chemistries_metadata.csv
    last_updated: '2024-06-01'
    row_count: 156
    vendor: israeli10k
  description: Comprehensive harmonization of chemistry tests from Arivale, UKBB NMR,
    and Israeli10k data sources
  tags:
  - chemistry
  - harmonization
  - multi_vendor
  - loinc
  - arivale
  - ukbb
  - israeli10k
  - comprehensive
  dependencies: []
  supersedes: null
  citation: null
  test_categories:
  - metabolic_panel
  - lipid_panel
  - complete_blood_count
  - liver_function
  - kidney_function
  - nmr_metabolomics
  - amino_acids
  - inflammatory_markers
parameters:
  output_dir: /tmp/biomapper_output
  cross_match_threshold: 0.75
  merge_strategy: union
  deduplicate_by: loinc_code
steps:
- name: load_arivale
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: test_name
      output_key: arivale_raw
- name: load_ukbb
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[1].path}
      identifier_column: biomarker
      output_key: ukbb_raw
- name: load_israeli10k
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[2].path}
      identifier_column: test_id
      output_key: israeli10k_raw
- name: extract_arivale_loinc
  action:
    type: CHEMISTRY_EXTRACT_LOINC
    params:
      input_key: arivale_raw
      vendor: arivale
      test_name_column: test_name
      loinc_column: loinc_code
      output_key: arivale_loinc
- name: extract_ukbb_loinc
  action:
    type: CHEMISTRY_EXTRACT_LOINC
    params:
      input_key: ukbb_raw
      vendor: ukbb_nmr
      biomarker_column: biomarker
      use_nightingale_mapping: true
      filter_clinical_only: true
      clinical_markers:
      - Total_C
      - LDL_C
      - HDL_C
      - Triglycerides
      - Glucose
      - Lactate
      - Alanine
      - Creatinine
      output_key: ukbb_loinc
- name: extract_israeli10k_loinc
  action:
    type: CHEMISTRY_EXTRACT_LOINC
    params:
      input_key: israeli10k_raw
      vendor: israeli10k
      test_id_column: test_id
      test_name_column: test_name_hebrew
      translate_hebrew: true
      output_key: israeli10k_loinc
- name: harmonize_arivale
  action:
    type: CHEMISTRY_VENDOR_HARMONIZATION
    params:
      input_key: arivale_loinc
      vendor: arivale
      harmonization_rules:
        glucose:
        - glucose
        - blood glucose
        - GLU
        cholesterol:
        - cholesterol
        - total cholesterol
        - CHOL
        ldl_cholesterol:
        - LDL cholesterol
        - LDL-C
        - LDL
        hdl_cholesterol:
        - HDL cholesterol
        - HDL-C
        - HDL
        triglycerides:
        - triglycerides
        - TG
        - TRIG
        hemoglobin:
        - hemoglobin
        - HGB
        - Hb
        hematocrit:
        - hematocrit
        - HCT
        - Hct
        creatinine:
        - creatinine
        - CREAT
        - CR
      output_key: arivale_harmonized
- name: harmonize_ukbb
  action:
    type: CHEMISTRY_VENDOR_HARMONIZATION
    params:
      input_key: ukbb_loinc
      vendor: ukbb
      harmonization_rules:
        glucose:
        - Glucose
        cholesterol:
        - Total_C
        - Total cholesterol
        ldl_cholesterol:
        - LDL_C
        - LDL cholesterol
        hdl_cholesterol:
        - HDL_C
        - HDL cholesterol
        triglycerides:
        - Triglycerides
        lactate:
        - Lactate
        - lactic acid
        alanine:
        - Alanine
        creatinine:
        - Creatinine
      output_key: ukbb_harmonized
- name: harmonize_israeli10k
  action:
    type: CHEMISTRY_VENDOR_HARMONIZATION
    params:
      input_key: israeli10k_loinc
      vendor: israeli10k
      harmonization_rules:
        glucose:
        - glucose
        - blood sugar
        - GLU
        - גלוקוז
        cholesterol:
        - cholesterol
        - CHOL
        - total cholesterol
        - כולסטרול
        hemoglobin:
        - hemoglobin
        - HGB
        - Hb
        - המוגלובין
        triglycerides:
        - triglycerides
        - TG
        - TRIG
        - טריגליצרידים
        ldl_cholesterol:
        - LDL cholesterol
        - LDL-C
        - LDL
        hdl_cholesterol:
        - HDL cholesterol
        - HDL-C
        - HDL
        creatinine:
        - creatinine
        - CREAT
        - CR
        - קריאטינין
        urea:
        - urea
        - BUN
        - blood urea nitrogen
        - אוריאה
      output_key: israeli10k_harmonized
- name: cross_vendor_fuzzy
  action:
    type: CHEMISTRY_FUZZY_TEST_MATCH
    params:
      source_datasets:
      - arivale_harmonized
      - ukbb_harmonized
      - israeli10k_harmonized
      cross_match: true
      match_threshold: ${parameters.cross_match_threshold}
      use_loinc_primary: true
      fallback_to_harmonized_name: true
      generate_cross_reference_table: true
      output_key: cross_matched
- name: merge_datasets
  action:
    type: MERGE_DATASETS
    params:
      dataset_keys:
      - arivale_harmonized
      - ukbb_harmonized
      - israeli10k_harmonized
      merge_strategy: ${parameters.merge_strategy}
      deduplicate_by: ${parameters.deduplicate_by}
      preserve_source_info: true
      conflict_resolution: prefer_loinc
      output_key: unified_chemistry
- name: calculate_multi_overlap
  action:
    type: CALCULATE_THREE_WAY_OVERLAP
    params:
      dataset1_key: arivale_harmonized
      dataset2_key: ukbb_harmonized
      dataset3_key: israeli10k_harmonized
      overlap_metric: loinc_code
      output_key: multi_vendor_statistics
- name: export_unified
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: unified_chemistry
      output_path: ${parameters.output_dir}/unified_chemistry_tests.tsv
      include_source_mapping: true
      include_harmonization_info: true
- name: export_cross_reference
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: cross_matched
      output_path: ${parameters.output_dir}/chemistry_cross_reference_table.tsv
      format: cross_reference_table
- name: export_statistics
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: multi_vendor_statistics
      output_path: ${parameters.output_dir}/multi_vendor_chemistry_statistics.json
      format: json
