name: chem_arv_to_kg2c_phenotypes_v1_base
description: Maps Arivale clinical chemistry/lab tests to KG2c phenotypic features
  via LOINC codes and semantic associations
metadata:
  id: chem_arv_to_kg2c_phenotypes_v1_base
  name: Arivale Chemistries to KG2c Phenotypes
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: chemistries
  source_dataset: arivale
  target_dataset: kg2c_phenotypes
  bridge_type:
  - loinc
  - semantic
  - rule_based
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.65
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/chemistries_metadata.tsv
    last_updated: '2019-06-01'
    row_count: 128
  target_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/kg2.10.2c_ontologies/kg2c_phenotypes.csv
    last_updated: '2024-10-01'
    row_count: 45000
  description: Maps clinical chemistry tests to phenotypic features for disease association
    analysis
  tags:
  - chemistries
  - phenotypes
  - loinc
  - clinical
  - arivale
  - kg2c
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/chemistries}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
  cache_ttl_days: 30
steps:
- name: load_arivale_chemistries
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: Name
      additional_columns:
      - Display Name
      - Labcorp ID
      - Labcorp Name
      - Labcorp LOINC ID
      output_key: arivale_chemistries
      drop_empty: true
- name: load_kg2c_phenotypes
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.target_files[0].path}
      identifier_column: id
      additional_columns:
      - name
      - category
      - description
      - synonyms
      - xrefs
      output_key: kg2c_phenotypes
      drop_empty: true
- name: extract_loinc_codes
  action:
    type: CHEMISTRY_EXTRACT_LOINC
    params:
      input_key: arivale_chemistries
      loinc_column: Labcorp LOINC ID
      test_name_column: Name
      display_name_column: Display Name
      output_key: arivale_with_loinc
- name: filter_clinical_phenotypes
  action:
    type: FILTER_DATASET
    params:
      dataset_key: kg2c_phenotypes
      filters:
      - field: category
        operator: contains
        value: PhenotypicFeature
      output_key: clinical_phenotypes
- name: bridge_chemistry_to_phenotypes
  action:
    type: CHEMISTRY_TO_PHENOTYPE_BRIDGE
    params:
      source_key: arivale_with_loinc
      target_key: clinical_phenotypes
      loinc_column: Labcorp LOINC ID
      phenotype_id_column: id
      phenotype_xrefs_column: xrefs
      association_threshold: 0.7
      use_semantic_matching: true
      output_key: chemistry_phenotype_mappings
- name: calculate_overlap
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      dataset1_key: arivale_with_loinc
      dataset2_key: clinical_phenotypes
      output_key: overlap_statistics
- name: export_mappings
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: chemistry_phenotype_mappings
      output_path: ${parameters.output_dir}/arivale_kg2c_chemistry_phenotypes.tsv
