name: met_multi_semantic_enrichment_v1_advanced
description: Advanced semantic matching with vector enhancement and combined match
  strategies
metadata:
  id: met_multi_semantic_enrichment_v1_advanced
  name: Semantic Metabolite Enrichment Pipeline
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: metabolites
  source_dataset: multi-source
  target_dataset: semantically-enriched
  bridge_type:
  - semantic
  - vector
  - combined
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.88
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/metabolomics_metadata.tsv
    last_updated: '2024-07-15'
    row_count: 4156
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_NMR_Meta.tsv
    last_updated: '2024-09-01'
    row_count: 249
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/kg2.10.2c_ontologies/kg2c_metabolites.csv
    last_updated: '2024-10-01'
    row_count: 28000
  target_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/spoke_ontologies/spoke_metabolites.csv
    last_updated: '2024-09-15'
    row_count: 25600
  description: Advanced semantic matching pipeline with vector enhancement and weighted
    combination strategies
  tags:
  - semantic
  - vector
  - advanced
  - enrichment
  - combined-matching
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/metabolites}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
  cache_ttl_days: 30
  nightingale_reference_file: /procedure/data/local_data/references/nightingale_nmr_reference.csv
  vector_model: mol2vec
  semantic_model: biobert
steps:
- name: load_arivale
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: metabolite_id
      output_key: arivale_raw
- name: load_ukbb_nmr
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[1].path}
      identifier_column: biomarker
      output_key: ukbb_nmr_raw
- name: load_kg2c_target
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[2].path}
      identifier_column: xrefs
      output_key: kg2c_target_raw
- name: load_spoke_target
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.target_files[0].path}
      identifier_column: identifiers
      output_key: spoke_target_raw
- name: extract_arivale_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: arivale_raw
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      compound_field: metabolite_id
      output_key: arivale_metabolites
- name: extract_ukbb_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: ukbb_nmr_raw
      biomarker_column: biomarker
      extract_hmdb: true
      extract_inchikey: false
      nmr_specific: true
      output_key: ukbb_metabolites
- name: extract_kg2c_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: kg2c_target_raw
      xrefs_column: xrefs
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      output_key: kg2c_metabolites
- name: extract_spoke_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: spoke_target_raw
      identifiers_column: identifiers
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      output_key: spoke_metabolites
- name: nightingale_match
  action:
    type: NIGHTINGALE_NMR_MATCH
    params:
      input_key: ukbb_metabolites
      biomarker_column: biomarker
      reference_file: ${parameters.nightingale_reference_file}
      match_threshold: 0.85
      fuzzy_matching: true
      enhanced_mode: true
      output_key: ukbb_nightingale_matched
- name: normalize_arivale_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: arivale_metabolites
      hmdb_column: metabolite_id
      target_format: HMDB0001234
      output_key: arivale_normalized
- name: normalize_ukbb_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: ukbb_nightingale_matched
      hmdb_column: hmdb_id
      target_format: HMDB0001234
      output_key: ukbb_normalized
- name: merge_sources
  action:
    type: MERGE_DATASETS
    params:
      dataset_keys:
      - arivale_normalized
      - ukbb_normalized
      merge_strategy: union
      deduplicate: true
      output_key: source_metabolites
- name: merge_targets
  action:
    type: MERGE_DATASETS
    params:
      dataset_keys:
      - kg2c_metabolites
      - spoke_metabolites
      merge_strategy: union
      deduplicate: true
      output_key: target_metabolites
- name: cts_bridge_baseline
  action:
    type: METABOLITE_CTS_BRIDGE
    params:
      source_key: source_metabolites
      target_key: target_metabolites
      source_id_type: hmdb
      target_id_type: inchikey
      chunk_size: 1000
      parallel_requests: 5
      cache_results: true
      output_key: cts_matched
- name: semantic_match
  action:
    type: SEMANTIC_METABOLITE_MATCH
    params:
      source_key: source_metabolites
      target_key: target_metabolites
      model: ${parameters.semantic_model}
      threshold: 0.8
      batch_size: 500
      use_compound_names: true
      use_descriptions: true
      output_key: semantic_matched
- name: vector_enhance
  action:
    type: VECTOR_ENHANCED_MATCH
    params:
      input_key: semantic_matched
      embedding_model: ${parameters.vector_model}
      similarity_metric: cosine
      min_similarity: 0.75
      enhance_weak_matches: true
      recalculate_scores: true
      output_key: vector_enhanced
- name: multi_bridge_fallback
  action:
    type: METABOLITE_MULTI_BRIDGE
    params:
      source_key: source_metabolites
      target_key: target_metabolites
      bridge_types:
      - hmdb
      - inchikey
      - chebi
      - kegg
      max_attempts: 3
      fallback_to_semantic: true
      only_unmatched: true
      previous_matches_key: vector_enhanced
      output_key: multi_bridge_matches
- name: combine_matches
  action:
    type: COMBINE_METABOLITE_MATCHES
    params:
      match_results:
      - key: cts_matched
        weight: 0.3
        confidence_boost: 0.1
      - key: semantic_matched
        weight: 0.25
        confidence_boost: 0.0
      - key: vector_enhanced
        weight: 0.25
        confidence_boost: 0.05
      - key: multi_bridge_matches
        weight: 0.2
        confidence_boost: 0.0
      combination_strategy: weighted_vote
      confidence_threshold: 0.7
      resolve_conflicts: true
      output_key: combined_matches
- name: generate_report
  action:
    type: GENERATE_METABOLOMICS_REPORT
    params:
      dataset_key: combined_matches
      include_statistics: true
      include_visualizations: true
      include_method_comparison: true
      include_confidence_analysis: true
      method_breakdown: true
      output_path: ${parameters.output_dir}/semantic_enrichment_report.html
- name: export_enriched_dataset
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: combined_matches
      output_path: ${parameters.output_dir}/semantically_enriched_metabolites.tsv
      include_confidence_scores: true
      include_method_provenance: true
      include_alternative_matches: true
- name: calculate_performance
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      dataset1_key: source_metabolites
      dataset2_key: target_metabolites
      analysis_type: comprehensive
      include_method_metrics: true
      output_key: performance_statistics
