name: met_multi_to_unified_semantic_v1_enhanced
description: Complex multi-source metabolite harmonization with semantic enhancement
metadata:
  id: met_multi_to_unified_semantic_v1_enhanced
  name: Multi-Source Metabolite Unified Analysis
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: metabolites
  source_dataset: multi-source
  target_dataset: unified
  bridge_type:
  - multi-bridge
  - semantic
  - vector
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.8
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/metabolomics_metadata.tsv
    last_updated: '2024-07-15'
    row_count: 4156
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_NMR_Meta.tsv
    last_updated: '2024-09-01'
    row_count: 249
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/israeli10k/israeli10k_metabolomics_metadata.csv
    last_updated: '2024-08-01'
    row_count: 3421
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/israeli10k/israeli10k_lipidomics_metadata.csv
    last_updated: '2024-08-01'
    row_count: 2834
  target_files: []
  description: Comprehensive multi-source metabolite harmonization with advanced semantic
    matching
  tags:
  - multi-source
  - semantic
  - harmonization
  - unified
  - advanced
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/metabolites}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
  cache_ttl_days: 30
  nightingale_reference_file: /procedure/data/local_data/references/nightingale_nmr_reference.csv
steps:
- name: load_arivale
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: metabolite_id
      output_key: arivale_raw
- name: load_ukbb_nmr
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[1].path}
      identifier_column: biomarker
      output_key: ukbb_nmr_raw
- name: load_israeli10k_metab
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[2].path}
      identifier_column: compound_id
      output_key: israeli10k_metab_raw
- name: load_israeli10k_lipid
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[3].path}
      identifier_column: lipid_id
      output_key: israeli10k_lipid_raw
- name: extract_arivale_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: arivale_raw
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      compound_field: metabolite_id
      output_key: arivale_extracted
- name: extract_ukbb_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: ukbb_nmr_raw
      biomarker_column: biomarker
      extract_hmdb: true
      extract_inchikey: false
      nmr_specific: true
      output_key: ukbb_extracted
- name: extract_israeli10k_metab_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: israeli10k_metab_raw
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: false
      extract_kegg: false
      output_key: israeli10k_metab_extracted
- name: extract_israeli10k_lipid_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: israeli10k_lipid_raw
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: false
      extract_kegg: false
      lipid_specific_parsing: true
      output_key: israeli10k_lipid_extracted
- name: nightingale_match
  action:
    type: NIGHTINGALE_NMR_MATCH
    params:
      input_key: ukbb_extracted
      biomarker_column: biomarker
      reference_file: ${parameters.nightingale_reference_file}
      match_threshold: 0.85
      fuzzy_matching: true
      output_key: ukbb_nightingale_matched
- name: normalize_arivale_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: arivale_extracted
      hmdb_column: metabolite_id
      target_format: HMDB0001234
      output_key: arivale_normalized
- name: normalize_ukbb_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: ukbb_nightingale_matched
      hmdb_column: hmdb_id
      target_format: HMDB0001234
      output_key: ukbb_normalized
- name: normalize_israeli10k_metab_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: israeli10k_metab_extracted
      hmdb_column: compound_id
      target_format: HMDB0001234
      output_key: israeli10k_metab_normalized
- name: normalize_israeli10k_lipid_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: israeli10k_lipid_extracted
      hmdb_column: lipid_id
      target_format: HMDB0001234
      output_key: israeli10k_lipid_normalized
- name: merge_datasets
  action:
    type: MERGE_DATASETS
    params:
      dataset_keys:
      - arivale_normalized
      - ukbb_normalized
      - israeli10k_metab_normalized
      - israeli10k_lipid_normalized
      merge_strategy: union
      deduplicate: true
      merge_on:
      - hmdb_id
      - inchikey
      output_key: merged_metabolites
- name: three_way_overlap
  action:
    type: CALCULATE_THREE_WAY_OVERLAP
    params:
      dataset1_key: arivale_normalized
      dataset2_key: ukbb_normalized
      dataset3_key: israeli10k_metab_normalized
      comparison_field: hmdb_id
      output_key: three_way_statistics
- name: semantic_enhancement
  action:
    type: SEMANTIC_METABOLITE_MATCH
    params:
      source_key: merged_metabolites
      target_key: merged_metabolites
      model: biobert
      threshold: 0.85
      self_matching: true
      cluster_similar: true
      output_key: semantically_enhanced
- name: export_unified
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: semantically_enhanced
      output_path: ${parameters.output_dir}/unified_metabolites.tsv
      include_metadata: true
      include_source_info: true
- name: export_statistics
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: three_way_statistics
      output_path: ${parameters.output_dir}/multi_source_statistics.tsv
      export_format: json
