name: met_arv_to_spoke_multi_v1_base
description: Maps Arivale metabolomics to SPOKE using comprehensive multi-bridge resolution
metadata:
  id: met_arv_to_spoke_multi_v1_base
  name: Arivale Metabolomics to SPOKE via Multi-Bridge
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: metabolites
  source_key: arivale
  target_key: spoke
  bridge_type:
  - hmdb
  - inchikey
  - chebi
  - kegg
  - semantic
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.76
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/metabolomics_metadata.tsv
    last_updated: '2024-07-15'
    row_count: 4156
  target_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/spoke_ontologies/spoke_metabolites.csv
    last_updated: '2024-09-15'
    row_count: 25600
  description: Maps Arivale metabolomics to SPOKE using multi-bridge resolution with
    semantic fallback
  tags:
  - metabolomics
  - multi-bridge
  - semantic
  - arivale
  - spoke
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/metabolites}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
  cache_ttl_days: 30
steps:
- name: load_arivale
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: metabolite_id
      output_key: arivale_metabolites_raw
- name: load_spoke
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.target_files[0].path}
      identifier_column: identifiers
      output_key: spoke_metabolites_raw
- name: extract_arivale_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: arivale_metabolites_raw
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      compound_field: metabolite_id
      output_key: arivale_metabolites
- name: extract_spoke_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: spoke_metabolites_raw
      identifiers_column: identifiers
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      output_key: spoke_metabolites
- name: normalize_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: arivale_metabolites
      hmdb_column: metabolite_id
      target_format: HMDB0001234
      output_key: arivale_normalized
- name: multi_bridge_spoke
  action:
    type: METABOLITE_MULTI_BRIDGE
    params:
      source_key: arivale_normalized
      target_key: spoke_metabolites
      bridge_types:
      - hmdb
      - inchikey
      - chebi
      - kegg
      max_attempts: 3
      fallback_to_semantic: true
      chunk_size: 1000
      parallel_requests: 5
      cache_results: true
      spoke_specific: true
      output_key: multi_mapped
- name: calculate_overlap
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      input_key: arivale_normalized
      dataset2_key: spoke_metabolites
      output_key: overlap_statistics
- name: export_mapping
  action:
    type: EXPORT_DATASET
    params:
      input_key: multi_mapped
      output_path: ${parameters.output_dir}/arivale_spoke_metabolites.tsv
