name: met_ukb_nmr_to_spoke_nightingale_v1_enhanced
description: Maps UKBB NMR to SPOKE with Nightingale reference matching and enhanced
  CTS bridge
metadata:
  id: met_ukb_nmr_to_spoke_nightingale_v1_enhanced
  name: UKBB NMR to SPOKE via Nightingale + CTS Enhanced
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: metabolites
  source_dataset: ukbb
  target_dataset: spoke
  bridge_type:
  - nightingale
  - hmdb
  - cts
  - semantic
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.85
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_NMR_Meta.tsv
    last_updated: '2024-09-01'
    row_count: 249
  target_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/spoke_ontologies/spoke_metabolites.csv
    last_updated: '2024-09-15'
    row_count: 25600
  description: Enhanced UKBB NMR to SPOKE mapping with Nightingale reference and CTS
    bridge optimization
  tags:
  - nmr
  - nightingale
  - ukbb
  - spoke
  - enhanced
  - biomarkers
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/metabolites}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
  cache_ttl_days: 30
  nightingale_reference_file: /procedure/data/local_data/references/nightingale_nmr_reference.csv
steps:
- name: load_ukbb_nmr
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: biomarker
      output_key: ukbb_nmr_raw
- name: load_spoke
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.target_files[0].path}
      identifier_column: identifiers
      output_key: spoke_metabolites_raw
- name: extract_ukbb_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: ukbb_nmr_raw
      biomarker_column: biomarker
      extract_hmdb: true
      extract_inchikey: false
      nmr_specific: true
      output_key: ukbb_nmr_metabolites
- name: extract_spoke_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: spoke_metabolites_raw
      identifiers_column: identifiers
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      output_key: spoke_metabolites
- name: nightingale_match
  action:
    type: NIGHTINGALE_NMR_MATCH
    params:
      input_key: ukbb_nmr_metabolites
      biomarker_column: biomarker
      reference_file: ${parameters.nightingale_reference_file}
      match_threshold: 0.85
      fuzzy_matching: true
      enhanced_mode: true
      output_key: nightingale_matched
- name: normalize_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: nightingale_matched
      hmdb_column: hmdb_id
      target_format: HMDB0001234
      output_key: ukbb_normalized
- name: cts_bridge_enhanced
  action:
    type: METABOLITE_CTS_BRIDGE
    params:
      source_key: ukbb_normalized
      target_key: spoke_metabolites
      source_id_type: hmdb
      target_id_type: inchikey
      chunk_size: 50
      parallel_requests: 2
      cache_results: true
      enhanced_mode: true
      retry_failed: true
      output_key: cts_enhanced
- name: semantic_fallback
  action:
    type: SEMANTIC_METABOLITE_MATCH
    params:
      source_key: cts_enhanced
      target_key: spoke_metabolites
      model: biobert
      threshold: 0.8
      nmr_specific: true
      output_key: semantic_matched
- name: calculate_overlap
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      dataset1_key: ukbb_normalized
      dataset2_key: spoke_metabolites
      output_key: overlap_statistics
- name: export_mapping
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: semantic_matched
      output_path: ${parameters.output_dir}/ukbb_nmr_spoke_enhanced.tsv
