name: met_arv_to_kg2c_multi_v1_base
description: Maps Arivale metabolomics to KG2c using multiple bridge resolution with
  semantic fallback
metadata:
  id: met_arv_to_kg2c_multi_v1_base
  name: Arivale Metabolomics to KG2c via Multi-Bridge
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: metabolites
  source_dataset: arivale
  target_dataset: kg2c
  bridge_type:
  - hmdb
  - inchikey
  - chebi
  - kegg
  - semantic
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.78
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/metabolomics_metadata.tsv
    last_updated: '2024-07-15'
    row_count: 4156
  target_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/kg2.10.2c_ontologies/kg2c_metabolites.csv
    last_updated: '2024-10-01'
    row_count: 28000
  description: Maps Arivale metabolomics to KG2c using comprehensive multi-bridge
    resolution with semantic fallback
  tags:
  - metabolomics
  - multi-bridge
  - semantic
  - arivale
  - kg2c
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/metabolites}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
  cache_ttl_days: 30
steps:
- name: load_arivale
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: metabolite_id
      output_key: arivale_metabolites_raw
- name: load_kg2c
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.target_files[0].path}
      identifier_column: xrefs
      output_key: kg2c_metabolites_raw
- name: extract_arivale_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: arivale_metabolites_raw
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      compound_field: metabolite_id
      output_key: arivale_metabolites
- name: extract_kg2c_ids
  action:
    type: METABOLITE_EXTRACT_IDENTIFIERS
    params:
      input_key: kg2c_metabolites_raw
      xrefs_column: xrefs
      extract_hmdb: true
      extract_inchikey: true
      extract_chebi: true
      extract_kegg: true
      output_key: kg2c_metabolites
- name: normalize_hmdb
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_key: arivale_metabolites
      hmdb_column: metabolite_id
      target_format: HMDB0001234
      output_key: arivale_normalized
- name: multi_bridge
  action:
    type: METABOLITE_MULTI_BRIDGE
    params:
      source_key: arivale_normalized
      target_key: kg2c_metabolites
      bridge_types:
      - hmdb
      - inchikey
      - chebi
      - kegg
      max_attempts: 3
      fallback_to_semantic: true
      chunk_size: 1000
      parallel_requests: 5
      cache_results: true
      output_key: multi_mapped
- name: calculate_overlap
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      dataset1_key: arivale_normalized
      dataset2_key: kg2c_metabolites
      output_key: overlap_statistics
- name: export_mapping
  action:
    type: EXPORT_DATASET
    params:
      dataset_key: multi_mapped
      output_path: ${parameters.output_dir}/arivale_kg2c_metabolites.tsv
