name: multi_disease_integration_v1_specialized
metadata:
  id: multi_disease_integration_v1_specialized
  name: Disease-Specific Multi-Omics Integration
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type:
  - proteins
  - metabolites
  - chemistry
  source_key:
  - disease_cohort
  - control_cohort
  target_key: disease_biomarkers
  bridge_type:
  - differential_analysis
  - biomarker_discovery
  - clinical_validation
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.8
  description: 'Integrate multi-omics data for specific disease analysis and biomarker

    discovery. This strategy performs comprehensive differential analysis

    across proteins, metabolites, and clinical chemistry between disease

    cases and healthy controls. Focuses on identifying disease-specific

    molecular signatures, validated biomarker panels, and potential

    therapeutic targets through multi-omics integration.

    '
  use_cases:
  - Disease biomarker discovery
  - Precision medicine development
  - Drug target identification
  - Diagnostic panel development
  - Disease mechanism elucidation
  disease_models:
    type_2_diabetes:
      clinical_criteria:
      - HbA1c >= 6.5%
      - Fasting glucose >= 126 mg/dL
      - Random glucose >= 200 mg/dL
      exclusion_criteria:
      - Type 1 diabetes
      - Gestational diabetes
      - Secondary diabetes
      biomarker_categories:
      - glucose_metabolism
      - lipid_metabolism
      - inflammation
      - insulin_signaling
    cardiovascular_disease:
      clinical_criteria:
      - Coronary artery disease
      - Myocardial infarction history
      - Stroke history
      biomarker_categories:
      - lipid_metabolism
      - inflammation
      - endothelial_function
      - coagulation
    metabolic_syndrome:
      clinical_criteria:
      - Waist circumference > threshold
      - Elevated triglycerides
      - Low HDL cholesterol
      - Elevated blood pressure
      - Elevated fasting glucose
      biomarker_categories:
      - metabolic_dysregulation
      - insulin_resistance
      - inflammation
  source_files:
  - path: /procedure/data/disease_cohorts/t2dm_cases/proteomics_cases.tsv
    entity: proteins
    cohort: cases
    disease: type_2_diabetes
    description: Type 2 diabetes protein measurements
  - path: /procedure/data/disease_cohorts/t2dm_cases/metabolomics_cases.tsv
    entity: metabolites
    cohort: cases
    disease: type_2_diabetes
    description: Type 2 diabetes metabolomics
  - path: /procedure/data/disease_cohorts/t2dm_cases/chemistry_cases.tsv
    entity: chemistry
    cohort: cases
    disease: type_2_diabetes
    description: Type 2 diabetes clinical chemistry
  - path: /procedure/data/disease_cohorts/healthy_controls/proteomics_controls.tsv
    entity: proteins
    cohort: controls
    disease: healthy
    description: Healthy control protein measurements
  - path: /procedure/data/disease_cohorts/healthy_controls/metabolomics_controls.tsv
    entity: metabolites
    cohort: controls
    disease: healthy
    description: Healthy control metabolomics
  - path: /procedure/data/disease_cohorts/healthy_controls/chemistry_controls.tsv
    entity: chemistry
    cohort: controls
    disease: healthy
    description: Healthy control clinical chemistry
  - path: /procedure/data/validation_cohorts/independent_validation.tsv
    entity: multi_omics
    cohort: validation
    description: Independent validation cohort
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/outputs}
  disease_focus: type_2_diabetes
  control_group: healthy_controls
  differential_analysis_method: limma
  biomarker_selection_method: random_forest
  cross_validation_folds: 10
  max_biomarkers: 50
  significance_threshold: 0.05
  effect_size_threshold: 1.2
  validation_required: true
steps:
- name: load_case_proteins
  description: Load protein data for disease cases
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: uniprot
      subject_id_column: subject_id
      phenotype_column: disease_status
      covariates:
      - age
      - sex
      - BMI
      - medication
      output_key: case_proteins_raw
- name: load_case_metabolites
  description: Load metabolite data for disease cases
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[1].path}
      identifier_column: hmdb_id
      subject_id_column: subject_id
      phenotype_column: disease_status
      concentration_column: concentration
      output_key: case_metabolites_raw
- name: load_case_chemistry
  description: Load clinical chemistry for disease cases
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[2].path}
      identifier_column: test_name
      subject_id_column: subject_id
      phenotype_column: disease_status
      value_column: test_value
      reference_ranges: true
      output_key: case_chemistry_raw
- name: load_control_proteins
  description: Load protein data for healthy controls
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[3].path}
      identifier_column: uniprot
      subject_id_column: subject_id
      phenotype_column: disease_status
      covariates:
      - age
      - sex
      - BMI
      output_key: control_proteins_raw
- name: load_control_metabolites
  description: Load metabolite data for healthy controls
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[4].path}
      identifier_column: hmdb_id
      subject_id_column: subject_id
      phenotype_column: disease_status
      concentration_column: concentration
      output_key: control_metabolites_raw
- name: load_control_chemistry
  description: Load clinical chemistry for healthy controls
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[5].path}
      identifier_column: test_name
      subject_id_column: subject_id
      phenotype_column: disease_status
      value_column: test_value
      reference_ranges: true
      output_key: control_chemistry_raw
- name: normalize_proteins
  description: Normalize and harmonize protein data
  action:
    type: PROTEIN_NORMALIZE_ACCESSIONS
    params:
      input_keys:
      - case_proteins_raw
      - control_proteins_raw
      batch_correction: true
      normalization_method: quantile
      outlier_detection: true
      output_key: proteins_normalized
- name: normalize_metabolites
  description: Normalize and harmonize metabolite data
  action:
    type: METABOLITE_NORMALIZE_HMDB
    params:
      input_keys:
      - case_metabolites_raw
      - control_metabolites_raw
      batch_correction: true
      normalization_method: log_transform
      missing_value_imputation: knn
      output_key: metabolites_normalized
- name: harmonize_chemistry
  description: Harmonize clinical chemistry measurements
  action:
    type: CHEMISTRY_VENDOR_HARMONIZATION
    params:
      input_keys:
      - case_chemistry_raw
      - control_chemistry_raw
      unit_standardization: true
      reference_range_normalization: true
      outlier_detection: true
      output_key: chemistry_harmonized
- name: protein_differential_analysis
  description: Perform differential analysis for proteins
  action:
    type: PROTEIN_MULTI_BRIDGE
    params:
      input_key: proteins_normalized
      analysis_type: differential_expression
      comparison: case_vs_control
      statistical_method: ${parameters.differential_analysis_method}
      covariates:
      - age
      - sex
      - BMI
      multiple_testing_correction: fdr
      significance_threshold: ${parameters.significance_threshold}
      effect_size_threshold: ${parameters.effect_size_threshold}
      output_key: protein_differential
- name: metabolite_differential_analysis
  description: Perform differential analysis for metabolites
  action:
    type: METABOLITE_CTS_BRIDGE
    params:
      input_key: metabolites_normalized
      analysis_type: differential_abundance
      comparison: case_vs_control
      statistical_method: metaboanalyst
      pathway_context: true
      multiple_testing_correction: fdr
      significance_threshold: ${parameters.significance_threshold}
      output_key: metabolite_differential
- name: chemistry_differential_analysis
  description: Perform differential analysis for clinical chemistry
  action:
    type: CHEMISTRY_FUZZY_TEST_MATCH
    params:
      input_key: chemistry_harmonized
      analysis_type: differential_clinical
      comparison: case_vs_control
      statistical_method: mann_whitney
      clinical_significance: true
      reference_range_analysis: true
      output_key: chemistry_differential
- name: integrate_differential_results
  description: Integrate differential analysis results across omics layers
  action:
    type: COMBINE_METABOLITE_MATCHES
    params:
      input_keys:
      - protein_differential
      - metabolite_differential
      - chemistry_differential
      combination_method: multi_omics_integration
      integration_strategy: pathway_based
      disease_focus: ${parameters.disease_focus}
      pathway_databases:
      - kegg
      - reactome
      - wikipathways
      output_key: integrated_differential
- name: pathway_enrichment_analysis
  description: Perform pathway enrichment on integrated results
  action:
    type: METABOLITE_API_ENRICHMENT
    params:
      input_key: integrated_differential
      enrichment_type: disease_pathway
      pathway_databases:
      - kegg
      - reactome
      - go_biological_process
      disease_context: ${parameters.disease_focus}
      min_pathway_size: 5
      max_pathway_size: 500
      fdr_threshold: 0.05
      output_key: pathway_enrichment
- name: feature_selection
  description: Select most informative features for biomarker panel
  action:
    type: SEMANTIC_METABOLITE_MATCH
    params:
      source_key: integrated_differential
      selection_method: ${parameters.biomarker_selection_method}
      cross_validation: true
      cv_folds: ${parameters.cross_validation_folds}
      max_features: ${parameters.max_biomarkers}
      feature_importance_threshold: 0.01
      stability_selection: true
      output_key: selected_biomarkers
- name: biomarker_panel_optimization
  description: Optimize biomarker panel composition
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      input_key: selected_biomarkers
      dataset2_key: pathway_enrichment
      optimization_criteria:
      - auc_score
      - sensitivity
      - specificity
      - clinical_interpretability
      panel_size_range:
      - 5
      - 20
      cross_validation: true
      output_key: optimized_biomarker_panel
- name: train_classification_models
  description: Train machine learning models for disease classification
  action:
    type: METABOLITE_API_ENRICHMENT
    params:
      input_key: optimized_biomarker_panel
      analysis_type: machine_learning
      models:
      - random_forest
      - support_vector_machine
      - gradient_boosting
      - logistic_regression
      cross_validation: true
      hyperparameter_tuning: true
      performance_metrics:
      - auc
      - sensitivity
      - specificity
      - ppv
      - npv
      output_key: ml_models
- name: model_interpretation
  description: Interpret machine learning models and feature importance
  action:
    type: SEMANTIC_METABOLITE_MATCH
    params:
      source_key: ml_models
      interpretation_method: shap
      feature_interaction_analysis: true
      pathway_context_interpretation: true
      clinical_relevance_scoring: true
      output_key: model_interpretation
- name: load_validation_cohort
  description: Load independent validation cohort
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[6].path}
      identifier_columns:
      - uniprot
      - hmdb_id
      - test_name
      subject_id_column: subject_id
      phenotype_column: disease_status
      multi_omics_format: true
      output_key: validation_cohort
- name: validate_biomarker_panel
  description: Validate biomarker panel on independent cohort
  action:
    type: CALCULATE_THREE_WAY_OVERLAP
    params:
      input_key: optimized_biomarker_panel
      dataset2_key: ml_models
      dataset3_key: validation_cohort
      validation_type: independent_cohort
      performance_metrics:
      - auc
      - sensitivity
      - specificity
      confidence_intervals: true
      bootstrap_samples: 1000
      output_key: validation_results
- name: clinical_significance_assessment
  description: Assess clinical significance of biomarker findings
  action:
    type: CHEMISTRY_FUZZY_TEST_MATCH
    params:
      input_key: validation_results
      clinical_assessment: true
      reference_standards: ${metadata.disease_models.${parameters.disease_focus}.clinical_criteria}
      diagnostic_performance: true
      clinical_utility_metrics: true
      cost_effectiveness: true
      output_key: clinical_significance
- name: therapeutic_target_identification
  description: Identify potential therapeutic targets
  action:
    type: PROTEIN_MULTI_BRIDGE
    params:
      input_key: integrated_differential
      target_identification: true
      druggability_assessment: true
      pathway_target_analysis: true
      literature_mining: true
      target_databases:
      - drugbank
      - chembl
      - therapeutic_target
      output_key: therapeutic_targets
- name: generate_disease_biomarker_report
  description: Generate comprehensive disease biomarker discovery report
  action:
    type: GENERATE_METABOLOMICS_REPORT
    params:
      input_key: validation_results
      report_type: disease_biomarker_discovery
      include_differential_analysis: true
      include_pathway_analysis: true
      include_biomarker_panels: true
      include_ml_performance: true
      include_validation_results: true
      include_clinical_significance: true
      differential_data_key: integrated_differential
      pathway_data_key: pathway_enrichment
      biomarker_data_key: optimized_biomarker_panel
      ml_data_key: ml_models
      interpretation_data_key: model_interpretation
      clinical_data_key: clinical_significance
      therapeutic_targets_key: therapeutic_targets
      disease_context: ${parameters.disease_focus}
      output_path: ${parameters.output_dir}/disease_biomarker_discovery_report.html
- name: export_biomarker_panels
  description: Export validated biomarker panels
  action:
    type: EXPORT_DATASET
    params:
      input_key: optimized_biomarker_panel
      output_path: ${parameters.output_dir}/validated_biomarker_panels.tsv
      format: tsv
      include_performance_metrics: true
      include_clinical_annotations: true
- name: export_differential_results
  description: Export differential analysis results
  action:
    type: EXPORT_DATASET
    params:
      input_key: integrated_differential
      output_path: ${parameters.output_dir}/multi_omics_differential_analysis.json
      format: json
      include_statistical_metrics: true
- name: export_ml_models
  description: Export trained machine learning models
  action:
    type: EXPORT_DATASET
    params:
      input_key: ml_models
      output_path: ${parameters.output_dir}/disease_classification_models.pkl
      format: pickle
      include_model_metadata: true
- name: export_therapeutic_targets
  description: Export identified therapeutic targets
  action:
    type: EXPORT_DATASET
    params:
      input_key: therapeutic_targets
      output_path: ${parameters.output_dir}/therapeutic_targets.tsv
      format: tsv
      include_druggability_scores: true
expected_outputs:
  primary:
  - path: ${parameters.output_dir}/validated_biomarker_panels.tsv
    description: Validated biomarker panels with performance metrics
    entity_types:
    - proteins
    - metabolites
    - chemistry
    - biomarkers
  models:
  - path: ${parameters.output_dir}/disease_classification_models.pkl
    description: Trained machine learning models for disease classification
  targets:
  - path: ${parameters.output_dir}/therapeutic_targets.tsv
    description: Identified therapeutic targets with druggability assessment
  analysis:
  - path: ${parameters.output_dir}/multi_omics_differential_analysis.json
    description: Comprehensive differential analysis results across omics layers
  reports:
  - path: ${parameters.output_dir}/disease_biomarker_discovery_report.html
    description: Comprehensive disease biomarker discovery report
validation:
  min_biomarkers_identified: 10
  max_execution_time_minutes: 40
  required_auc_score: 0.75
  required_validation_cohort: true
  min_therapeutic_targets: 5
  clinical_significance_required: true
