name: production_uniprot_only
description: Production pipeline filtering KG2c to only UniProtKB entries for efficient
  matching
version: '1.0'
parameters:
  arivale_file: /procedure/data/local_data/ARIVALE_SNAPSHOTS/proteomics_metadata.tsv
  kg2c_file: /procedure/data/local_data/MAPPING_ONTOLOGIES/kg2c_ontologies/kg2c_proteins.csv
  arivale_id_column: uniprot
  kg2c_id_column: id
  output_dir: /tmp/biomapper_results
  timestamp: '2024-12-14'
  drive_folder_id: 1lqOX1pWP_CbZn-mU5InVt6lG7-uaj8Hn
steps:
- name: load_arivale
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${parameters.arivale_file}
      identifier_column: ${parameters.arivale_id_column}
      output_key: arivale_proteins
- name: load_kg2c
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${parameters.kg2c_file}
      identifier_column: ${parameters.kg2c_id_column}
      output_key: kg2c_all_entities
- name: filter_kg2c_uniprot
  action:
    type: FILTER_DATASET
    params:
      input_key: kg2c_all_entities
      output_key: kg2c_uniprot_only
      filter_column: ${parameters.kg2c_id_column}
      filter_type: contains
      filter_value: 'UniProtKB:'
- name: uniprot_resolution
  action:
    type: MERGE_WITH_UNIPROT_RESOLUTION
    params:
      input_key: arivale_proteins
      target_dataset_key: kg2c_uniprot_only
      source_id_column: ${parameters.arivale_id_column}
      target_id_column: ${parameters.kg2c_id_column}
      target_xref_column: xrefs
      composite_separator: _
      use_api: true
      api_batch_size: 100
      output_key: mapping_results
- name: export_results
  action:
    type: EXPORT_DATASET
    params:
      input_key: mapping_results
      output_path: ${parameters.output_dir}/protein_mapping_results.csv
      format: csv
- name: export_kg2c_filtered
  action:
    type: EXPORT_DATASET
    params:
      input_key: kg2c_uniprot_only
      output_path: ${parameters.output_dir}/kg2c_uniprot_only.csv
      format: csv
- name: export_arivale
  action:
    type: EXPORT_DATASET
    params:
      input_key: arivale_proteins
      output_path: ${parameters.output_dir}/arivale_proteins.csv
      format: csv
- name: export_summary
  action:
    type: EXPORT_DATASET
    params:
      input_key: mapping_results
      output_path: ${parameters.output_dir}/summary.json
      format: json
- name: google_drive_sync
  action:
    type: SYNC_TO_GOOGLE_DRIVE_V2
    params:
      local_directory: ${parameters.output_dir}
      drive_folder_id: ${parameters.drive_folder_id}
      strategy_name: production_uniprot_only
      timestamp: ${parameters.timestamp}
      include_patterns:
      - '*.csv'
      - '*.json'
      auto_organize: true
      create_summary: true
