name: Arivale to UKBB Protein Comparison
description: Cross-dataset protein comparison between Arivale and UKBB proteomics
  using UniProt bridges
metadata:
  id: prot_arv_ukb_comparison_uniprot_v1_base
  name: Arivale to UKBB Protein Comparison
  version: 1.0.0
  created: '2025-01-08'
  author: biomapper-team
  entity_type: proteins
  source_key: arivale
  target_key: ukbb
  bridge_type:
  - uniprot
  quality_tier: experimental
  validation_status: pending
  expected_match_rate: 0.85
  actual_match_rate: null
  source_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/proteomics_metadata.tsv
    last_updated: '2024-06-01'
    row_count: 1197
  target_files:
  - path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_Protein_Meta.tsv
    last_updated: '2024-10-01'
    row_count: 2500
  description: Cross-dataset protein comparison between Arivale and UKBB proteomics
    using UniProt accessions as bridge
  tags:
  - proteomics
  - uniprot
  - ukbb
  - arivale
  - comparison
  dependencies: []
  supersedes: null
  citation: null
parameters:
  output_dir: /tmp/biomapper_results/prot_arv_ukb_comparison
steps:
- name: load_arivale_proteins
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/arivale/proteomics_metadata.tsv
      identifier_column: uniprot
      output_key: arivale_proteins
- name: load_ukbb_proteins
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: /procedure/data/local_data/MAPPING_ONTOLOGIES/ukbb/UKBB_Protein_Meta.tsv
      identifier_column: uniprot
      output_key: ukbb_proteins
- name: normalize_arivale
  action:
    type: PROTEIN_NORMALIZE_ACCESSIONS
    params:
      input_key: arivale_proteins
      output_key: arivale_normalized
- name: normalize_ukbb
  action:
    type: PROTEIN_NORMALIZE_ACCESSIONS
    params:
      input_key: ukbb_proteins
      output_key: ukbb_normalized
- name: multi_bridge_resolution
  action:
    type: PROTEIN_MULTI_BRIDGE
    params:
      source_key: arivale_normalized
      target_key: ukbb_normalized
      bridge_types:
      - uniprot
      - gene_symbol
      output_key: mapped_proteins
- name: calculate_overlap
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      input_key: arivale_normalized
      dataset2_key: ukbb_normalized
      output_key: overlap_statistics
- name: export_results
  action:
    type: EXPORT_DATASET
    params:
      input_key: mapped_proteins
      output_path: ${parameters.output_dir}/protein_comparison.tsv
