name: TEMPLATE_PROTEIN_MAPPING
description: Standardized protein mapping with UniProt historical resolution
metadata:
  id: ${source}_to_${target}_uniprot_unified
  name: ${Source} to ${Target} Protein Mapping
  version: 2.0.0
  created: '2025-01-13'
  author: biomapper-team
  entity_type: proteins
  source_key: ${source}
  target_key: ${target}
  bridge_type:
  - uniprot
  - historical_resolution
  quality_tier: production
  validation_status: validated
  expected_match_rate: 0.85
  source_files:
  - path: ${source_file_path}
    identifier_column: ${source_id_column}
  target_files:
  - path: ${target_file_path}
    identifier_column: ${target_id_column}
parameters:
  output_dir: ${OUTPUT_DIR:-/tmp/biomapper/proteins}
  cache_dir: ${CACHE_DIR:-/tmp/biomapper/cache}
  use_cache: true
steps:
- name: load_source_dataset
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.source_files[0].path}
      identifier_column: ${metadata.source_files[0].identifier_column}
      output_key: source_raw
- name: load_target_dataset
  action:
    type: LOAD_DATASET_IDENTIFIERS
    params:
      file_path: ${metadata.target_files[0].path}
      identifier_column: ${metadata.target_files[0].identifier_column}
      output_key: target_raw
- name: extract_source_uniprot
  action:
    type: PROTEIN_EXTRACT_UNIPROT_FROM_XREFS
    params:
      input_key: source_raw
      xrefs_column: ${metadata.source_files[0].identifier_column}
      remove_isoforms: true
      output_key: source_extracted
  conditional: ${needs_source_extraction}
- name: extract_target_uniprot
  action:
    type: PROTEIN_EXTRACT_UNIPROT_FROM_XREFS
    params:
      input_key: target_raw
      xrefs_column: ${metadata.target_files[0].identifier_column}
      remove_isoforms: true
      output_key: target_extracted
  conditional: ${needs_target_extraction}
- name: normalize_source_accessions
  action:
    type: PROTEIN_NORMALIZE_ACCESSIONS
    params:
      input_key: ${source_working_key}
      accession_column: uniprot
      remove_versions: true
      remove_isoforms: true
      uppercase: true
      output_key: source_normalized
- name: normalize_target_accessions
  action:
    type: PROTEIN_NORMALIZE_ACCESSIONS
    params:
      input_key: ${target_working_key}
      accession_column: uniprot
      remove_versions: true
      remove_isoforms: true
      uppercase: true
      output_key: target_normalized
- name: direct_uniprot_match
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      input_key: source_normalized
      dataset2_key: target_normalized
      id_column1: uniprot
      id_column2: uniprot
      output_key: direct_match_stats
- name: uniprot_historical_resolution
  action:
    type: MERGE_WITH_UNIPROT_RESOLUTION
    params:
      input_key: source_normalized
      target_dataset_key: target_normalized
      source_id_column: uniprot
      target_id_column: uniprot
      use_api: true
      api_batch_size: 100
      api_cache_results: true
      confidence_threshold: 0.8
      output_key: resolved_proteins
- name: multi_bridge_unresolved
  action:
    type: PROTEIN_MULTI_BRIDGE
    params:
      source_key: resolved_proteins
      target_key: target_normalized
      bridge_types:
      - gene_symbol
      - ensembl
      - refseq
      max_attempts: 3
      only_unmatched: true
      output_key: fully_mapped
- name: filter_high_confidence
  action:
    type: FILTER_DATASET
    params:
      input_key: fully_mapped
      filter_criteria:
        confidence: '>= 0.7'
        has_uniprot: true
      output_key: high_confidence_proteins
- name: calculate_final_overlap
  action:
    type: CALCULATE_SET_OVERLAP
    params:
      input_key: source_normalized
      dataset2_key: high_confidence_proteins
      output_key: final_statistics
- name: generate_mapping_report
  action:
    type: GENERATE_MAPPING_REPORT
    params:
      mapping_key: high_confidence_proteins
      statistics_key: final_statistics
      include_unmapped: true
      include_confidence_distribution: true
      output_key: mapping_report
- name: export_mapped_proteins
  action:
    type: EXPORT_DATASET
    params:
      input_key: high_confidence_proteins
      output_format: tsv
      output_path: ${parameters.output_dir}/mapped_proteins.tsv
      include_metadata: true
- name: export_unmapped_source
  action:
    type: EXPORT_DATASET
    params:
      input_key: source_normalized
      filter_unmapped: true
      output_format: tsv
      output_path: ${parameters.output_dir}/unmapped_source.tsv
- name: export_statistics
  action:
    type: EXPORT_DATASET
    params:
      input_key: final_statistics
      output_format: json
      output_path: ${parameters.output_dir}/mapping_statistics.json
