name: prot_ukb_to_kg2c_uniprot_v1_base
description: Map UKBB proteins to RTX-KG2c via UniProt
parameters:
  ukbb_proteins_file: "/tmp/protein_test_data/ukbb_proteins.tsv"
  output_dir: "/tmp/protein_test_results/ukb_kg2c"
  identifier_column: "protein_id"
  description_column: "protein_description"
steps:
  - name: load_ukbb_proteins
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.ukbb_proteins_file}"
        identifier_column: "${parameters.identifier_column}"
        description_column: "${parameters.description_column}"
        output_key: ukbb_proteins
  - name: map_to_uniprot
    action:
      type: MERGE_WITH_UNIPROT_RESOLUTION
      params:
        input_key: ukbb_proteins
        output_key: mapped_proteins
        confidence_threshold: 0.8
  - name: export_results
    action:
      type: EXPORT_DATASET
      params:
        input_key: mapped_proteins
        output_dir: "${parameters.output_dir}"
        output_filename: "ukbb_kg2c_mapping.tsv"
        format: tsv