name: prot_arv_to_spoke_uniprot_v1_base
description: Map Arivale proteins to SPOKE via UniProt
parameters:
  arivale_proteins_file: "/tmp/protein_test_data/arivale_proteins.tsv"
  output_dir: "/tmp/protein_test_results/arv_spoke"
  identifier_column: "uniprot_id"
  description_column: "protein_name"
steps:
  - name: load_arivale_proteins
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.arivale_proteins_file}"
        identifier_column: "${parameters.identifier_column}"
        description_column: "${parameters.description_column}"
        output_key: arivale_proteins
  - name: map_to_spoke
    action:
      type: EXECUTE_MAPPING_PATH
      params:
        input_key: arivale_proteins
        output_key: spoke_mapped
        mapping_path: "uniprot_to_spoke"
  - name: export_results
    action:
      type: EXPORT_DATASET
      params:
        input_key: spoke_mapped
        output_dir: "${parameters.output_dir}"
        output_filename: "arivale_spoke_mapping.tsv"
        format: tsv