name: prot_arv_to_kg2c_uniprot_v1_base
description: Map Arivale proteins to RTX-KG2c via UniProt
parameters:
  arivale_proteins_file: "/tmp/protein_test_data/arivale_proteins.tsv"
  output_dir: "/tmp/protein_test_results/arv_kg2c"
  identifier_column: "uniprot_id"
  description_column: "protein_name"
steps:
  - name: load_arivale_proteins
    action:
      type: LOAD_DATASET_IDENTIFIERS
      params:
        file_path: "${parameters.arivale_proteins_file}"
        identifier_column: "${parameters.identifier_column}"
        description_column: "${parameters.description_column}"
        output_key: arivale_proteins
  - name: map_to_uniprot
    action:
      type: MERGE_WITH_UNIPROT_RESOLUTION
      params:
        input_key: arivale_proteins
        output_key: mapped_proteins
        confidence_threshold: 0.8
  - name: export_results
    action:
      type: EXPORT_DATASET
      params:
        input_key: mapped_proteins
        output_dir: "${parameters.output_dir}"
        output_filename: "arivale_kg2c_mapping.tsv"
        format: tsv