name: Biomapper CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    
    - name: Load cached dependencies
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install dependencies for biomapper
      run: |
        poetry install --no-interaction --no-root
        poetry install --no-interaction
    
    - name: Install dependencies for biomapper-api
      working-directory: ./biomapper-api
      run: |
        poetry install --no-interaction --no-root
        poetry install --no-interaction
    
    - name: Run tests
      env:
        DATABASE_URL: "sqlite+aiosqlite:///./test.db"
      run: |
        poetry run pytest -m "not requires_qdrant and not requires_external_services"